### ISSUE TITLE
提示从可能出现的错误

### ISSUE THREAD

**Issue by StasToken** [huobiapi/REST-PHP-demo#5]
提示从可能出现的错误 
我使用你的例子，把所有的键允许访问，但是当你运行查询得到一个响应。 

> {"status":"error","err-code":"account-get-balance-account-inexistent-error","err-msg":"account for id `55,477,925` and user id `5,547,792` is not exist","data":null}

如何理解这个问题？

**Comment by huobiapi** [comment]
请先用：[get accounts 接口](https://github.com/huobiapi/API_Docs/wiki/REST_api_reference#get-v1accountaccounts) 获取您的account-id，这个account-id就是其他所有接口中需要上传的account-id参数
